services:
    app:
        build:
            context: .
            target: dev
        ports:
            - "8080:8080"
        env_file:
            - dev.env
        depends_on:
            database:
                condition: service_healthy
        develop:
            watch:
                - action: rebuild
                  path: ./src
    database:
        image: mysql:8.0.36-bookworm
        ports:
            - "3306:3306"
        env_file:
            - dev.env
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10