version: '3.1'

services:
  database:
    image: mysql:8.0.36-bookworm
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: bank-systems
      MYSQL_ROOT_PASSWORD: secure