datasource:
    host: localhost
    port: 3306
    user: user
    password: password
    database: bank-systems
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}
    schema:
        generation:
            strategy: create-drop
    show_sql: true
app:
    pagination:
        max_size: 50
    path: /banking
server:
    host: localhost
    port: 8080
    virtual_threads: true
