datasource:
    host: localhost
    port: 3306
    user: user
    password: password
    database: bank-systems
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}
    schema:
        generation:
            strategy: drop-and-create
app:
    mode:
      debug: true
    pagination:
        max_size: 50
        default_size: 17
    path: /banking
server:
    host: localhost
    port: 8080
    virtual_threads: true
